#!/bin/bash

check_drv_abi_compat() {
    echo "The proprietary nvidia driver may not be ABI compatabile with"
    echo "this kernel version. It is strongly recommended to install the"
    echo "proprietrary nvidia driver with a seperate kernel build to avoid"
    echo "system instability issues."

    exit 0
}

setup_drv() {
	dri="$1"

	if [[ -z "$dri" ]]; then
		error 1 "no graphics driver selected"
	fi

    pkgs=( xorg xserver-xorg xserver-xorg-input-libinput )

	case "$dri" in
    *NOUVEAU*)      pkgs+=( xserver-xorg-video-nouveau ) ;;
    *Intel*)        pkgs+=( xserver-xorg-video-intel ) ;;
	*NVIDIA*)       check_drv_abi_compat ;;
    *ATI*|*AMD*)    pkgs+=( xserver-xorg-video-ati firmware-linux-nonfree libgl1-mesa-dri ) ;;
	*)              error 1 "invalid driver selection: %s" "$dri" ;;
	esac

	apt update || true
	apt -y upgrade
	apt install -y "${pkgs[@]}"

	printf "reboot system to load GPU device firmware\\n"
    exit 0
}

setup_vga() {
    base_pkgs=( xorg-server xf86-input-libinput eudev )

    apt get install pciutils eudev
    vgaline=$(lspci | grep -w VGA)

    case "$vgaline" in
    *Intel*) drv="xf86-video-intel" ;;
    *AMD*) drv="xf86-video-amdgpu" ;;
    *NOUVEAU*) drv="xf86-video-nouveau" ;;
    *VMWARE*) drv="xf86-vmware" ;;
    *QXL*) drv="x86-video-qxl" ;;
    esac

    # fallback driver
    drv="$drv xf86-video-modesetting"
    apt update || true
    apt -y upgrade
    apt-get install -y "${base_pkgs[@]}" $drv

    exit 0
}

get_dwm_pkgs() {
    apt-get install -y \
        libx11-dev \
        libxft-dev \
        libxinerama-dev \
        fonts-inconsolata \
        xorg \
        xserver-xorg \
		pciutils \
        xserver-xorg-input-libinput

    apt autoremove
    apt aucoclean
    apt clean
}

error() {
	error="$1" fmt="$2"
	shift; shift;
	# shellcheck disable=SC2059
	(printf "error: $fmt\\n" "$@" ) >&2
	exit "$error"
}

usage() {
	cat <<-EOF
	$(basename "$O") [COMMAND] [ARG...]
	Installs packages for the display server

	setup-drv-pkgs [intel] [amd|ati] [nouveau]
		install video/graphics driver packages
	setup-vga-pkgs [intel] [amd|ati] [nouveau] [nvidia] [vmware] [qxl]
		install vga packages
	get_dwm_pkgs
		install xlib development header dependencies for dwm
	help
		print this help
	EOF
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

cmd="$1"
while(($# > 0)); do
    case "$cmd" in
        drv)
            shift
            setup_drv_pkgs "$1"
            ;;
        vga)
            shift
            setup_vga_pkgs "$1"
            ;;
        dwm-pkgs)
            get_dwm_pkgs
            ;;
        help)
            usage; exit 0
            ;;
        *)
            usage; error 1 "%s is not a valid command" "$cmd"
            ;;
    esac
done
